### ISSUE TITLE
ReferenceError: window is not defined 

### ISSUE THREAD

**Issue by Rojina99** [mondago/ucclient-js-sdk#3]
After installing ucclient and importing as  const ucsession = require('ucclient-sdk'); I get error 

D:\NodeJSProject\hello\node_modules\ucclient-sdk\dist\index.js:1
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports["ucclient-sdk"]=t():e["ucclient-sdk"]=t()}(window,function(){return function(e){var t={};function n(a){if(t[a])return t[a].exports;var l=t[a]={i:a,l:!1,exports:{}};return e[a].call(l.exports,l,l.exports,n),l.l=!0,l.exports}return n.m=e,n.c=t,n.d=function(e,t,a){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:a})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var a=Object.create(null);if(n.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var l in e)n.d(a,l,function(t){return e[t]}.bind(null,l));return a

ReferenceError: window is not defined
    at Object.<anonymous> (D:\NodeJSProject\hello\node_modules\ucclient-sdk\dist\index.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\NodeJSProject\hello\server.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)

I am not sure why this error occurs. Can anyone help me out with this ?

I also wanted to know do I need to install gointegrator for package to run and if yes should I also have to configure telephony to use this package.

**Comment by ccpdouglas** [comment]
Hi @Rojina99 thanks for sending this over. I apologise for the late reply.

I believe the issue is, that you're trying to use the SDK in a Node.js project. Hence window is not defined because it does not exist. For it to work, you'll have to run it in a browser/client-side project.

And regarding your second question, yes you will have to install and configure your telephony client to run this.

Thanks,
Callum
